#ifndef JSON_C_SERIALIZER_CONFIG_H
#define JSON_C_SERIALIZER_CONFIG_H


#define JCS_CFG_ENDIAN_LIL 0
#define JCS_CFG_ENDIAN_BIG 1

#define JCS_CFG_ENDIAN_SYS JCS_CFG_ENDIAN_LIL


#endif // JSON_C_SERIALIZER_CONFIG_H